---
# Rubocop overrides


Gemspec/RequiredRubyVersion:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/RegexpLiteral:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
